# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20171010_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
