# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20171010_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='model.Manufacturer'),
        ),
    ]
