# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20171010_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuser',
            old_name='follower',
            new_name='following',
        ),
    ]
